algoritmo "15"

var
 sexo:caractere
 altura:real
 peso:real
inicio
 escreval("Digite a sua altura: ")
 leia(altura)
 escreval("Digite o sexo (F p/Feminino e M p/ Masculino)")
 leia(sexo)
   se sexo="m" entao
     peso:=(72.7*altura)-58
     escreval("seu Sexo é: ",sexo," O seu peso ideal é: ",peso)
   senao
     pesso:=(62.1*h)-44.7
     escreval("seu Sexo é: ",sexo," O seu peso ideal é: ",peso)
   fimse
fimalgoritmo
